micronaut:
  application:
    name: postservicemicronaut
netty:
  default:
    allocator:
      max-order: 3

datasources:
    default:
        url: jdbc:postgresql://localhost:5432/tccspringboot
        username: postgres
        password: admin
        driverClassName: org.postgresl.Driver
        dialect: POSTGRES


jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

