micronaut:
  application:
    name: postservicemicronaut
datasources:
    default:
        url: jdbc:h2:mem:testdb
        username: sa
        password: "password"
        driverClassName: org.h2.Driver
netty:
  default:
    allocator:
      max-order: 3


